/**
 * Schema examples extracted from schema metadata
 * These are used to generate rich tool documentation with varied examples
 */

import { PostType } from '../types/schemas/index.js';

export const SCHEMA_EXAMPLES: Record<PostType, any[]> = {
  event: [
    {
      id: 123,
      title: 'Summer Music Festival',
      slug: 'summer-music-festival',
      status: 'publish',
      type: 'tribe_events',
      start_date: '2024-07-15 18:00:00',
      end_date: '2024-07-15 23:00:00',
      all_day: false,
      timezone: 'America/Los_Angeles',
    },
    {
      id: 124,
      title: 'Conference Next Week',
      slug: 'conference-next-week',
      status: 'publish',
      type: 'tribe_events',
      start_date: 'next monday 9am',
      end_date: 'next friday 5pm',
      all_day: false,
      timezone: 'America/New_York',
      venues: [456],
      organizers: [789],
    },
    {
      id: 125,
      title: 'All Day Workshop',
      slug: 'all-day-workshop',
      status: 'publish',
      type: 'tribe_events',
      start_date: 'tomorrow',
      end_date: 'tomorrow',
      all_day: true,
      timezone: 'Europe/London',
      cost: 'Free',
    },
    {
      id: 126,
      title: 'Monthly Meetup',
      slug: 'monthly-meetup',
      status: 'publish',
      type: 'tribe_events',
      start_date: 'first thursday of next month 6:30pm',
      end_date: 'first thursday of next month 9:00pm',
      all_day: false,
      timezone: 'America/Chicago',
      description: 'Our regular monthly community meetup',
    },
    {
      id: 127,
      title: 'Holiday Party',
      slug: 'holiday-party',
      status: 'draft',
      type: 'tribe_events',
      start_date: 'December 15, 2024 7:00 PM',
      end_date: 'December 15, 2024 11:30 PM',
      all_day: false,
      timezone: 'America/Denver',
      venues: [789],
      cost: '$25 per person',
    },
    {
      id: 128,
      title: 'Weekend Retreat',
      slug: 'weekend-retreat',
      status: 'publish',
      type: 'tribe_events',
      start_date: 'last friday of march 2025',
      end_date: 'last sunday of march 2025',
      all_day: false,
      timezone: 'America/Phoenix',
      website: 'https://example.com/retreat',
    },
    {
      id: 129,
      title: 'Quick Meeting',
      slug: 'quick-meeting',
      status: 'publish',
      type: 'tribe_events',
      start_date: '+2 hours',
      end_date: '+3 hours',
      all_day: false,
      timezone: 'UTC',
    },
    {
      id: 130,
      title: 'Annual Gala',
      slug: 'annual-gala',
      status: 'publish',
      type: 'tribe_events',
      start_date: '2025-02-14 18:00:00',
      end_date: '2025-02-14 23:59:59',
      all_day: false,
      timezone: 'America/Los_Angeles',
      venues: [101, 102],
      organizers: [102, 103],
      cost: '$150',
      categories: [10, 11],
      tags: [20, 21],
    },
    {
      id: 131,
      title: 'Morning Yoga',
      slug: 'morning-yoga',
      status: 'publish',
      type: 'tribe_events',
      start_date: 'next saturday 6:30am',
      end_date: 'next saturday 8:00am',
      all_day: false,
      timezone: 'Asia/Tokyo',
      cost: '¥2000',
    },
    {
      id: 132,
      title: 'Tech Talk',
      slug: 'tech-talk',
      status: 'pending',
      type: 'tribe_events',
      start_date: '3 days',
      end_date: '3 days 1 hour',
      all_day: false,
      timezone: 'Europe/Berlin',
      description: 'Learn about the latest in web development',
      excerpt: 'A technical presentation on modern web technologies',
    },
  ],

  venue: [
    {
      id: 456,
      title: 'City Convention Center',
      slug: 'city-convention-center',
      status: 'publish',
      type: 'tribe_venue',
      address: '123 Main Street',
      city: 'San Francisco',
      state: 'CA',
      zip: '94102',
      country: 'United States',
      geo_lat: 37.7749,
      geo_lng: -122.4194,
    },
    {
      id: 457,
      title: 'The Grand Ballroom',
      slug: 'the-grand-ballroom',
      status: 'publish',
      type: 'tribe_venue',
      venue: 'Grand Ballroom at the Historic Hotel',
      address: '456 Park Avenue',
      city: 'New York',
      state: 'NY',
      zip: '10022',
      country: 'USA',
      phone: '+1 (212) 555-0123',
      website: 'https://grandballroom.example.com',
    },
    {
      id: 458,
      title: 'Community Park Amphitheater',
      slug: 'community-park-amphitheater',
      status: 'publish',
      type: 'tribe_venue',
      address: '789 Oak Street',
      city: 'Austin',
      state: 'TX',
      state_province: 'Texas',
      zip: '78701',
      country: 'United States',
      stateprovince: 'TX',
    },
    {
      id: 459,
      title: 'Virtual Event Space',
      slug: 'virtual-event-space',
      status: 'publish',
      type: 'tribe_venue',
      venue: 'Online',
      website: 'https://zoom.us/meeting',
    },
    {
      id: 460,
      title: 'London Conference Centre',
      slug: 'london-conference-centre',
      status: 'publish',
      type: 'tribe_venue',
      address: '42 Westminster Bridge Rd',
      city: 'London',
      province: 'Greater London',
      zip: 'SE1 7UT',
      country: 'United Kingdom',
      phone: '+44 20 7946 0958',
      geo_lat: 51.4975,
      geo_lng: -0.1357,
    },
    {
      id: 461,
      title: 'Beachside Resort',
      slug: 'beachside-resort',
      status: 'draft',
      type: 'tribe_venue',
      venue: 'Sunset Beach Resort & Spa',
      address: '1000 Coastal Highway',
      city: 'Miami Beach',
      state: 'FL',
      zip: '33139',
      country: 'US',
      phone: '305-555-BEACH',
      website: 'https://sunsetbeachresort.example.com',
      geo_lat: 25.7906,
      geo_lng: -80.1300,
    },
    {
      id: 462,
      title: 'Tokyo International Forum',
      slug: 'tokyo-international-forum',
      status: 'publish',
      type: 'tribe_venue',
      address: '3 Chome-5-1 Marunouchi',
      city: 'Chiyoda City',
      state_province: 'Tokyo',
      zip: '100-0005',
      country: 'Japan',
      phone: '+81 3-5221-9000',
      website: 'https://www.t-i-forum.co.jp/en/',
      geo_lat: 35.6769,
      geo_lng: 139.7639,
    },
  ],

  organizer: [
    {
      id: 789,
      title: 'Local Arts Council',
      slug: 'local-arts-council',
      status: 'publish',
      type: 'tribe_organizer',
      email: 'info@localartscouncil.org',
      website: 'https://localartscouncil.org',
      phone: '(555) 123-4567',
    },
    {
      id: 790,
      title: 'DJ Mike Stevens',
      slug: 'dj-mike-stevens',
      status: 'publish',
      type: 'tribe_organizer',
      organizer: 'Mike Stevens - Professional DJ',
      email: 'bookings@djmikestevens.com',
      phone: '+1-555-DJ-MIKE',
      website: 'https://djmikestevens.example.com',
    },
    {
      id: 791,
      title: 'Tech Innovators Conference Group',
      slug: 'tech-innovators-conference-group',
      status: 'publish',
      type: 'tribe_organizer',
      organizer: 'TechInnov Conference Management',
      email: 'events@techinnovators.io',
      website: 'https://conference.techinnovators.io',
    },
    {
      id: 792,
      title: 'Sarah Johnson',
      slug: 'sarah-johnson',
      status: 'publish',
      type: 'tribe_organizer',
      organizer: 'Sarah Johnson - Yoga Instructor',
      email: 'sarah@mindfulyoga.com',
      phone: '555-YOGA-NOW',
    },
    {
      id: 793,
      title: 'Municipal Recreation Department',
      slug: 'municipal-recreation-department',
      status: 'publish',
      type: 'tribe_organizer',
      phone: '(555) 867-5309',
      email: 'recreation@cityname.gov',
      website: 'https://recreation.cityname.gov',
    },
    {
      id: 794,
      title: 'The Green Earth Foundation',
      slug: 'the-green-earth-foundation',
      status: 'publish',
      type: 'tribe_organizer',
      organizer: 'Green Earth Environmental Foundation',
      email: 'contact@greenearth.org',
      website: 'https://www.greenearth.org',
      phone: '1-800-GO-GREEN',
    },
  ],

  ticket: [
    {
      id: 101,
      title: 'General Admission',
      slug: 'general-admission',
      status: 'publish',
      type: 'tec_tc_ticket',
      event: 123,
      price: 25.00,
      stock: 100,
      capacity: 100,
      sku: 'GA-2024-001',
    },
    {
      id: 102,
      title: 'VIP Pass',
      slug: 'vip-pass',
      status: 'publish',
      type: 'tec_tc_ticket',
      event: 123,
      price: 150.00,
      stock: 20,
      capacity: 30,
      availability: {
        status: 'available',
        available: 10,
        sold: 10,
        pending: 0,
      },
      sku: 'VIP-2024-001',
    },
    {
      id: 103,
      title: 'Free TC Ticket',
      slug: 'free-tc-ticket',
      status: 'publish',
      type: 'tec_tc_ticket',
      event: 124,
      // Note: No price field - WordPress defaults to 0 for free tickets
      stock: 500,
      provider: 'Tickets Commerce',
      sku: 'FREE-TC-001',
    },
    {
      id: 104,
      title: 'Free RSVP Ticket',
      slug: 'free-rsvp-ticket',
      status: 'publish',
      type: 'tribe_rsvp_tickets',
      event: 124,
      // Note: No price field - RSVP tickets are always free
      stock: 30,
      provider: 'RSVP',
      sku: 'RSVP-FREE-001',
    },
    {
      id: 104,
      title: 'Early Bird Special',
      slug: 'early-bird-special',
      status: 'publish',
      type: 'tec_tc_ticket',
      event: 125,
      price: 75.00,
      sale_price: 45.00,
      sale_price_start_date: '2024-12-01',
      sale_price_end_date: '2024-12-15',
      start_date: '2024-11-20 09:00:00',
      end_date: '2025-01-15 18:00:00',
      stock: 50,
      capacity: 50,
      availability: {
        status: 'sold_out',
        available: 0,
        sold: 50,
        pending: 0,
      },
      sku: 'EB-CONF-2024',
    },
    {
      id: 105,
      title: 'Student Discount',
      slug: 'student-discount',
      status: 'publish',
      type: 'tec_tc_ticket',
      event: 126,
      price: 15.00,
      stock: 75,
      capacity: 100,
      availability: {
        status: 'available',
        available: 25,
        sold: 70,
        pending: 5,
      },
      sku: 'STU-DISC-001',
    },
    {
      id: 106,
      title: 'Group Package (10 people)',
      slug: 'group-package-10',
      status: 'publish',
      type: 'tec_tc_ticket',
      event: 127,
      price: 200.00,
      stock: 10,
      sku: 'GRP-10-PKG',
    },
    {
      id: 107,
      title: 'Unlimited VIP Access',
      slug: 'unlimited-vip-access',
      status: 'publish',
      type: 'tec_tc_ticket',
      event: 128,
      price: 500.00,
      stock: -1,
      stock_mode: 'unlimited',
      sku: 'UNLIMITED-VIP-001',
    },
    {
      id: 108,
      title: 'Free Unlimited Community Access',
      slug: 'free-unlimited-community',
      status: 'publish',
      type: 'tec_tc_ticket',
      event: 129,
      // Note: No price field for free tickets - WordPress defaults to 0
      stock: -1,
      stock_mode: 'unlimited',
      sku: 'FREE-UNLIMITED-001',
    },
  ],
};
