import { z } from 'zod';
import { BasePostSchema } from './base.js';

/**
 * Ticket availability schema
 */
const TicketAvailabilitySchema = z.object({
  status: z.enum(['available', 'sold_out', 'unavailable'])
    .describe('Current availability status'),
  available: z.number().describe('Number of tickets currently available'),
  sold: z.number().describe('Number of tickets sold'),
  pending: z.number().describe('Number of tickets in pending transactions'),
}).meta({
  title: 'Ticket Availability',
  description: 'Real-time ticket inventory and sales information',
});

/**
 * Ticket post type schema
 */
export const TicketSchema = BasePostSchema.extend({
  type: z.union([
    z.literal('tribe_rsvp_tickets'),
    z.literal('tec_tc_ticket'),
  ]).describe('Ticket post type identifier (RSVP or paid ticket)'),
  event: z.number().optional().describe('ID of the associated event'),
  price: z.string().optional().describe('Ticket price (formatted with currency)'),
  stock: z.number().optional().describe('Total number of tickets available'),
  capacity: z.number().optional().describe('Maximum capacity for this ticket type'),
  availability: TicketAvailabilitySchema.optional()
    .describe('Current availability information'),
  sku: z.string().optional().describe('Stock keeping unit for inventory tracking'),
  provider: z.string().optional().describe('Ticketing provider (e.g., RSVP, Ticket Commerce, WooCommerce)'),
  rsvp: z.boolean().optional().describe('Whether this is a free RSVP ticket'),
}).meta({
  title: 'Ticket',
  description: 'Event ticket or RSVP type with pricing and availability information',
  examples: [
    {
      id: 101,
      title: 'General Admission',
      slug: 'general-admission',
      status: 'publish',
      type: 'tec_tc_ticket',
      event: 123,
      price: '$25.00',
      stock: 100,
      capacity: 100,
      sku: 'GA-2024-001',
      provider: 'WooCommerce',
    },
    {
      id: 102,
      title: 'VIP Pass',
      slug: 'vip-pass',
      status: 'publish',
      type: 'tec_tc_ticket',
      event: 123,
      price: '$150.00',
      stock: 20,
      capacity: 30,
      availability: {
        status: 'available',
        available: 10,
        sold: 10,
        pending: 0,
      },
      sku: 'VIP-2024-001',
      provider: 'WooCommerce',
    },
    {
      id: 103,
      title: 'Free Community RSVP',
      slug: 'free-community-rsvp',
      status: 'publish',
      type: 'tribe_rsvp_tickets',
      event: 124,
      price: 'Free',
      stock: 500,
      capacity: 500,
      rsvp: true,
      provider: 'RSVP',
    },
    {
      id: 104,
      title: 'Early Bird Special',
      slug: 'early-bird-special',
      status: 'publish',
      type: 'tec_tc_ticket',
      event: 125,
      price: '$45.00',
      stock: 50,
      capacity: 50,
      availability: {
        status: 'sold_out',
        available: 0,
        sold: 50,
        pending: 0,
      },
      sku: 'EB-CONF-2024',
    },
    {
      id: 105,
      title: 'Student Discount',
      slug: 'student-discount',
      status: 'publish',
      type: 'tec_tc_ticket',
      event: 126,
      price: '$15.00',
      stock: 75,
      capacity: 100,
      availability: {
        status: 'available',
        available: 25,
        sold: 70,
        pending: 5,
      },
      sku: 'STU-DISC-001',
      provider: 'WooCommerce',
    },
    {
      id: 106,
      title: 'Group Package (10 people)',
      slug: 'group-package-10',
      status: 'publish',
      type: 'tec_tc_ticket',
      event: 127,
      price: '$200.00',
      stock: 10,
      capacity: 10,
      sku: 'GRP-10-PKG',
    },
    {
      id: 107,
      title: 'Workshop Registration',
      slug: 'workshop-registration',
      status: 'draft',
      type: 'tribe_rsvp_tickets',
      event: 128,
      stock: 30,
      capacity: 30,
      rsvp: true,
      availability: {
        status: 'available',
        available: 30,
        sold: 0,
        pending: 0,
      },
    },
    {
      id: 108,
      title: 'Premium Seating',
      slug: 'premium-seating',
      status: 'publish',
      type: 'tec_tc_ticket',
      event: 129,
      price: '€75.00',
      stock: 40,
      capacity: 50,
      availability: {
        status: 'available',
        available: 15,
        sold: 25,
        pending: 0,
      },
      sku: 'PREM-SEAT-EU',
      provider: 'WooCommerce',
    },
    {
      id: 109,
      title: 'Livestream Access',
      slug: 'livestream-access',
      status: 'publish',
      type: 'tec_tc_ticket',
      event: 130,
      price: '$10.00',
      stock: 1000,
      capacity: 1000,
      sku: 'LIVE-STREAM-001',
      provider: 'WooCommerce',
    },
    {
      id: 110,
      title: 'Sponsor Table',
      slug: 'sponsor-table',
      status: 'private',
      type: 'tec_tc_ticket',
      event: 131,
      price: '$5000.00',
      stock: 8,
      capacity: 10,
      availability: {
        status: 'available',
        available: 2,
        sold: 6,
        pending: 0,
      },
      sku: 'SPONSOR-TABLE',
    },
    {
      id: 111,
      title: 'Day Pass',
      slug: 'day-pass',
      status: 'publish',
      type: 'tec_tc_ticket',
      event: 132,
      price: '¥3500',
      stock: 200,
      capacity: 200,
      provider: 'WooCommerce',
      sku: 'DAY-PASS-JP',
    },
    {
      id: 112,
      title: 'Waitlist Registration',
      slug: 'waitlist-registration',
      status: 'publish',
      type: 'tribe_rsvp_tickets',
      event: 133,
      rsvp: true,
      availability: {
        status: 'unavailable',
        available: 0,
        sold: 100,
        pending: 0,
      },
    },
  ],
});

/**
 * Type export
 */
export type Ticket = z.infer<typeof TicketSchema>;