import { z } from 'zod';
import { BasePostSchema, BasePostRequestSchema } from './base.js';

/**
 * Venue post type schema
 */
export const VenueSchema = BasePostSchema.extend({
  type: z.literal('tribe_venue').describe('Venue post type identifier'),
  venue: z.string().optional().describe('Venue name (may differ from post title)'),
  address: z.string().optional().describe('Street address'),
  city: z.string().optional().describe('City name'),
  state_province: z.string().optional().describe('State or province name'),
  state: z.string().optional().describe('State abbreviation (US)'),
  province: z.string().optional().describe('Province name (non-US)'),
  zip: z.string().optional().describe('ZIP or postal code'),
  country: z.string().optional().describe('Country name or code'),
  phone: z.string().optional().describe('Contact phone number'),
  website: z.string().optional().describe('Venue website URL'),
  stateprovince: z.string().optional().describe('Combined state/province field'),
  geo_lat: z.number().optional().describe('Latitude coordinate'),
  geo_lng: z.number().optional().describe('Longitude coordinate'),
}).meta({
  title: 'Venue',
  description: 'Location where events take place, including address and contact information',
  examples: [
    {
      id: 456,
      title: 'City Convention Center',
      slug: 'city-convention-center',
      status: 'publish',
      type: 'tribe_venue',
      address: '123 Main Street',
      city: 'San Francisco',
      state: 'CA',
      zip: '94102',
      country: 'United States',
      geo_lat: 37.7749,
      geo_lng: -122.4194,
    },
    {
      id: 457,
      title: 'The Grand Ballroom',
      slug: 'the-grand-ballroom',
      status: 'publish',
      type: 'tribe_venue',
      venue: 'Grand Ballroom at the Historic Hotel',
      address: '456 Park Avenue',
      city: 'New York',
      state: 'NY',
      zip: '10022',
      country: 'USA',
      phone: '+1 (212) 555-0123',
      website: 'https://grandballroom.example.com',
    },
    {
      id: 458,
      title: 'Community Park Amphitheater',
      slug: 'community-park-amphitheater',
      status: 'publish',
      type: 'tribe_venue',
      address: '789 Oak Street',
      city: 'Austin',
      state: 'TX',
      state_province: 'Texas',
      zip: '78701',
      country: 'United States',
      stateprovince: 'TX',
    },
    {
      id: 459,
      title: 'Virtual Event Space',
      slug: 'virtual-event-space',
      status: 'publish',
      type: 'tribe_venue',
      venue: 'Online',
      website: 'https://zoom.us/meeting',
    },
    {
      id: 460,
      title: 'London Conference Centre',
      slug: 'london-conference-centre',
      status: 'publish',
      type: 'tribe_venue',
      address: '42 Westminster Bridge Rd',
      city: 'London',
      province: 'Greater London',
      zip: 'SE1 7UT',
      country: 'United Kingdom',
      phone: '+44 20 7934 9999',
      geo_lat: 51.4975,
      geo_lng: -0.1357,
    },
    {
      id: 461,
      title: 'Beachside Resort',
      slug: 'beachside-resort',
      status: 'draft',
      type: 'tribe_venue',
      venue: 'Sunset Beach Resort & Spa',
      address: '1000 Coastal Highway',
      city: 'Miami Beach',
      state: 'FL',
      zip: '33139',
      country: 'US',
      phone: '305-555-BEACH',
      website: 'https://sunsetbeachresort.example.com',
      geo_lat: 25.7906,
      geo_lng: -80.1300,
    },
    {
      id: 462,
      title: 'Tokyo International Forum',
      slug: 'tokyo-international-forum',
      status: 'publish',
      type: 'tribe_venue',
      address: '3 Chome-5-1 Marunouchi',
      city: 'Chiyoda City',
      state_province: 'Tokyo',
      zip: '100-0005',
      country: 'Japan',
      phone: '+81 3-5221-9000',
      website: 'https://www.t-i-forum.co.jp/en/',
      geo_lat: 35.6769,
      geo_lng: 139.7639,
    },
    {
      id: 463,
      title: 'Private Residence',
      slug: 'private-residence',
      status: 'private',
      type: 'tribe_venue',
      city: 'Beverly Hills',
      state: 'CA',
      country: 'USA',
    },
    {
      id: 464,
      title: 'University Lecture Hall',
      slug: 'university-lecture-hall',
      status: 'publish',
      type: 'tribe_venue',
      venue: 'Smith Hall Room 201',
      address: '500 University Drive',
      city: 'Stanford',
      state: 'CA',
      zip: '94305',
      country: 'United States',
      phone: '(650) 723-2300',
    },
    {
      id: 465,
      title: 'Outdoor Festival Grounds',
      slug: 'outdoor-festival-grounds',
      status: 'pending',
      type: 'tribe_venue',
      venue: 'Riverside Park Festival Area',
      address: 'Riverside Park',
      city: 'Portland',
      state: 'OR',
      state_province: 'Oregon',
      zip: '97201',
      country: 'USA',
      geo_lat: 45.5152,
      geo_lng: -122.6784,
    },
  ],
});

/**
 * Venue request schema for creating/updating venues
 * Based on the TEC REST API Venue_Request_Body schema
 */
export const VenueRequestSchema = BasePostRequestSchema.extend({
  // Venue-specific fields
  address: z.string().optional().describe('The venue address'),
  country: z.string().optional().describe('The venue country'),
  city: z.string().optional().describe('The venue city'),
  state_province: z.string().optional().describe('The venue state/province'),
  state: z.string().optional().describe('The venue state'),
  province: z.string().optional().describe('The venue province'),
  zip: z.string().optional().describe('The venue zip code'),
  phone: z.string().optional().describe('The venue phone number'),
  website: z.string().url().optional().describe('The venue website'),
  
  // Pro-specific geolocation fields
  lat: z.number().optional().describe('The latitude of the venue'),
  lng: z.number().optional().describe('The longitude of the venue'),
}).meta({
  title: 'Venue Request Body',
  description: 'Schema for creating or updating venue posts via the REST API',
  examples: [
    {
      title: 'The Grand Ballroom',
      status: 'publish',
      address: '456 Park Avenue',
      city: 'New York',
      state: 'NY',
      zip: '10022',
      country: 'USA',
      phone: '+1 (212) 555-0123',
      website: 'https://grandballroom.example.com',
    },
    {
      title: 'Beachside Resort',
      address: '1000 Coastal Highway',
      city: 'Miami Beach',
      state: 'FL',
      zip: '33139',
      country: 'US',
      phone: '305-555-BEACH',
      website: 'https://sunsetbeachresort.example.com',
      lat: 25.7906,
      lng: -80.13,
    },
    {
      title: 'Virtual Event Space',
      website: 'https://zoom.us/meeting',
    },
  ],
});

/**
 * Type exports
 */
export type Venue = z.infer<typeof VenueSchema>;
export type VenueRequest = z.infer<typeof VenueRequestSchema>;