#!/usr/bin/env node
/**
 * Build script to generate PHP file with MCP tool definitions for AI Service
 */

import { getToolDefinitionsForPhp } from '../shared/tool-definitions.js';

/**
 * Generate the PHP file content
 */
function generatePhpFile(): string {
  const toolDefinitionsJson = getToolDefinitionsForPhp();
  
  return `<?php
/**
 * MCP Tool Definitions for The Events Calendar
 * 
 * This file is auto-generated by the MCP server build process.
 * DO NOT EDIT MANUALLY - changes will be lost on next build.
 * 
 * Generated on: ${new Date().toISOString()}
 * 
 * @package TheEventsCalendar
 * @subpackage MCP
 */

// Prevent direct access.
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

// For direct inclusion, return the tool definitions.
return json_decode( '${toolDefinitionsJson}', true );
`;
}

/**
 * Main build function
 */
async function build() {
  try {
    // Generate PHP content
    const phpContent = generatePhpFile();
    
    // Output to stdout for piping
    process.stdout.write(phpContent);
    
  } catch (error) {
    console.error('❌ Build failed:', error);
    process.exit(1);
  }
}

// Run the build
build();